/** ---------------------------------------------------------------------------------------------------------------------
 * @file generate-world-map.ts
 * @fileOverview bakes the world land outline into `src/shared/components/locations-map/world-land.ts`, so the
 *               locations map ships as plain inline SVG with no runtime D3 or CDN fetch. Run once, and again
 *               only if the view box or projection below changes:
 *
 *                   bun tools/generate-world-map.ts
 *
 * @note d3-geo / topojson-client / world-atlas are devDependencies used only here. The component reprojects
 *       markers with the same Mercator formula using the SCALE / TX / TY constants this script emits.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { geoMercator, geoPath } from 'd3-geo';
import { feature, mesh } from 'topojson-client';
import type { Topology, GeometryCollection } from 'topojson-specification';
import topo from 'world-atlas/countries-110m.json';

const WIDTH = 1400;
const HEIGHT = 640;
const PADDING = 20;
/** Antarctica is dropped and the poles are trimmed so the inhabited world fills the frame. */
const BOX = { type: 'MultiPoint', coordinates: [[-168, -56], [180, -56], [180, 76], [-168, 76]] } as const;

const world = topo as unknown as Topology<{ countries: GeometryCollection }>;
const projection = geoMercator().fitExtent(
  [[PADDING, PADDING], [WIDTH - PADDING, HEIGHT - PADDING]],
  BOX as never,
);
const path = geoPath(projection);

const countries = feature(world, world.objects.countries);
const inhabited = {
  ...countries,
  features: countries.features.filter((f) => (f.properties as { name?: string })?.name !== 'Antarctica'),
};
const land = path(inhabited) ?? '';
const borders = path(mesh(world, world.objects.countries, (a, b) => a !== b)) ?? '';

const round = (value: string) => value.replace(/(\d+\.\d{2})\d+/g, '$1');
const [tx, ty] = projection.translate();

const out = `/** ---------------------------------------------------------------------------------------------------------------------
 * @file world-land.ts
 * @fileOverview GENERATED by tools/generate-world-map.ts — do not edit by hand. World land outline and
 *               country borders as SVG path data, plus the Mercator constants that place markers on it.
 */
export const WORLD_WIDTH = ${WIDTH};
export const WORLD_HEIGHT = ${HEIGHT};
/** geoMercator scale / translate after fitting the inhabited world into the view box. */
export const WORLD_PROJECTION = { scale: ${projection.scale()}, tx: ${tx}, ty: ${ty} };
export const LAND_PATH = ${JSON.stringify(round(land))};
export const BORDERS_PATH = ${JSON.stringify(round(borders))};
`;

const target = resolve(import.meta.dir, '../src/shared/components/locations-map/world-land.ts');
writeFileSync(target, out);
console.log(`Wrote ${target} (${(out.length / 1024).toFixed(0)} KB)`);
